### ISSUE TITLE
pgcluu_collectd : defunct child process in Incremental mode

### ISSUE THREAD

**Issue by OrioQuezac** [darold/pgcluu#104] opened 2019-05-28 14:59 UTC
In incremental mode (--rotate-daily & --rotate-hourly) all child processes "pgcluu_collectd" are not stopped by the parent process.

Step to reproduce : 
```
$ pgcluu_collectd -i 60 --rotate-hourly -p 1520 /tmp/pgcluu --compress --pid-file=/tmp/pgcluu_collectd.1.pid

*** pgcluu_collectd v2.9 (pid:25580) started at Tue May 28 14:12:18 2019
Type Ctrl+c to quit.

LOG: compressing directory 2019/05/28/14 using /bin/gzip.
LOG: compressing directory 2019/05/28/15 using /bin/gzip.
```
Wait an hour and run `ps` :
```
$ ps -ef | grep pgcluu
postgres 25580  3621  0 14:12 pts/0    00:00:00 pgcluu_collectd
postgres 27558 25580  0 16:55 pts/0    00:00:00 [pgcluu_collectd] <defunct>
postgres 28116 25580  0 16:56 pts/0    00:00:00 [pgcluu_collectd] <defunct>
root     28656  9423  0 16:56 pts/1    00:00:00 grep --color=auto pgcluu
```

**Comment by daamien** [comment] 2019-10-28 13:36
Hello @darold  :)

We can't reproduce the problem with version 3.0.  You can consider this issue as fixed and close it.

Thanks again and see you soon !

**Comment by darold** [comment] 2019-10-28 18:46
Hi, thanks @daamien ! I will close it in few days, I will reopen it if @OrioQuezac can still reproduce the issue with v3.0.

**Comment by daamien** [comment] 2019-11-08 14:48
Hello @darold  !

@OrioQuezac is part of dalibo, I let you guess who he is :-)

Anyway we closed this issue internally, so  we won't react further on this one. 

See you soon

**Comment by darold** [comment] 2019-11-08 15:03
Ok so I guess it can be closed.

**Closed by darold** 2019-11-08 15:03 UTC
