### ISSUE TITLE
Statement statistics page does not horizontal scroll in Chrome

### ISSUE THREAD

**Issue by michaelcrobinson** [darold/pgcluu#45] opened 2015-06-11 18:00 UTC
Hi there,

The statement statistics page does not appear to wrap long queries in either Chrome or Safari. In Safari this is less of an issue as I can horizontally scroll over to see the statistics, but in Chrome I cannot horizontally scroll this page.

While I'm guessing the scrolling issue is more to do with Chrome, our company's standard browser is Chrome, so when I demo this tool to management I'll have to use Safari. But for readability sake, it would be preferred if the entire table was constrained to the size of the browser window and the values in the Query column wrapped instead of forcing an extreme width.

Let me know if you require a screenshot.

**Comment by darold** [comment] 2015-06-11 19:21
Hi,

I do not have this kind of issue in report "Statements statistics on XXX database" . I have tested Firefox 38.0, Chromium Version 37.0.2062.120 and ChromeVersion 43.0.2357.125 without being able to reproduce the issue. Or perhaps I'm not looking at the right report? You can add a screenshot, we will be fixed.

I this is the right report, please check that there is not a long string without space character, especially between list of column name, that prevent the query to be resize in the column. If this is the case adding a space will help to fix your issue but could break the query if it is not well placed.

Regards

**Comment by michaelcrobinson** [comment] 2015-06-11 19:30
My Chrome version is 43.0.2357.124 (64-bit), and Safari version is 8.0.6

The top screenshot is Chrome, and the bottom is Safari.

![screenshot_chrome](https://cloud.githubusercontent.com/assets/12733725/8116132/4e875a1c-104e-11e5-9290-97a97e13b764.png)

![screenshot_safari](https://cloud.githubusercontent.com/assets/12733725/8116135/537cdb46-104e-11e5-844d-72ea636974b7.png)

As you can see there is plenty of whitespace; it's pretty standard SQL. My only other guess would be that they're enclosed in double quotes at the start and end of each statement, but I've never seen quoted strings do that before...

**Comment by darold** [comment] 2015-06-11 20:03
Hum, I'm very surprised that your queries are enclosed with double quote, could you give me the version of PostgreSQL and pgCluu? Also can you send to my private email gilles@darold.net the html file perstats/database-queries-hub.html so that I will be able to check what's going wrong.

**Comment by darold** [comment] 2015-06-11 20:24
Ok, as I though, the query causing this problem is the following:

     WITH ranks AS ( SELECT experience_points AS leaderboard_points. contacts.*. rank() OVER (ORDER BY experience_points DESC) AS rank FROM contacts JOIN (SELECT events.contact_id. sum(points) AS experience_points FROM events WHERE experience_id = ? GROUP BY events.contact_id) as experience_events ON experience_events.contact_id = contacts.id WHERE contacts.type = ? AND contacts.locked_at IS NULL AND contacts.user_id IS NOT NULL AND contacts.id IN(?.?.?.?.?.?.?.?.?.?.?.?.?.?.?.?.?.?.?.?.?.?.?.?.?.?.?.?.?.?.?.?.?.?.?.?.?.?.?.?.?.?.?.?.?.?.?.?.?.?.?.?.?.?.?.?.?.?.?.?.?.?.?.?.?.?.?.?.?.?.?.?.?.?.?.?.?.?.?.?.?.?.?.?.?.?.?.?.?.?.?.?.?.?.?.?.?.?.?.?.?.?.?.?.?. ...

You can see a long non-space separated string with question mark and dot, this is the reason of the issue.

This is very strange I don't understand why you have such a replacement, could you send me  privately the data file pg_stat_statements.csv ? It will help me to understand why you have such reformatted queries.

**Comment by michaelcrobinson** [comment] 2015-06-11 20:34
Ok I see that now.

I think we can safely close this. I'll bring this to the attention of the
dev team, they might not have been aware this is a thing. It doesn't appear
to be a heavily used query and may just need some code clean up.

Thank you for your assistance. I'll close the issue in github.

**Closed** 2015-06-11 20:34 UTC
