### ISSUE TITLE
Browser Memory Consumption: Database info page

### ISSUE THREAD

**Issue by aschrafl** [darold/pgcluu#119] opened 2021-01-01 10:43 UTC
When opening the database info page the browsers memory consumption goes wild (indefinitely, I maxed it out at 16GB, after that it is no longer responsive). This is on a low traffic database set to show a single day on the graphs. The other pages (the ones without graphs) work, so I assume it has something to do with the graphing engine.

I use pgCluu 3.1 installed on Debian Buster and tested this on Firefox, Chromium running on Linux and OpenBSD.

**Comment by darold** [comment] 2021-01-03 10:11
I guess that you are using the CGI mode but are you executing the sa_cache command to build the cache? This command must be run periodically through a cron job, for example each five or ten minutes. Without this cache, pgcluu must load in memory several statistic files data to compute the report.

**Comment by aschrafl** [comment] 2021-01-07 19:20
No I'm generating the reports statically via the timer. Was running pgcluu_collectd and pgcluu services via the timer.

**Comment by aschrafl** [comment] 2021-01-07 19:45
Checking the generated reports are pretty large. The database-NAME.html files are over 40MB for a day. Should they be this large? Or is there any way to reduce the sampling frequency I missed?

**Comment by darold** [comment] 2021-01-08 08:55
Ok I see, 40MB is far too high for an HTML page. Give me few days I will split this page into several parts, there is too much formation on a single page. Please can you post the result of the following command to see which other reports shall need to be splitted :
```
ls -lah reportdirectory/ | sed -E 's/[^ ]+-(table|index|missing|redundant|count|unused)/dbname-\1/' | sed -E 's/(database(-queries)?).*.html/\1-dbname.html/'
```
the command will anonymize your database name.

**Comment by aschrafl** [comment] 2021-01-09 09:45
-rw-r----- 1 postgres www-data 3.4M Jan  7 00:22 cluster-archive.html
-rw-r----- 1 postgres www-data 3.4M Jan  7 00:22 cluster-bgwriter_count.html
-rw-r----- 1 postgres www-data 1.9M Jan  7 00:22 cluster-bgwriter_read.html
-rw-r----- 1 postgres www-data 5.0M Jan  7 00:21 cluster-bgwriter_write.html
-rw-r----- 1 postgres www-data 3.4M Jan  7 00:22 cluster-checkpoints.html
-rw-r----- 1 postgres www-data 3.4M Jan  7 00:22 cluster-checkpoints_time.html
-rw-r----- 1 postgres www-data 8.0M Jan  7 00:22 cluster-database-dbname.html
-rw-r----- 1 postgres www-data 6.0M Jan  7 00:21 cluster-database-dbname.html
-rw-r----- 1 postgres www-data 8.0M Jan  7 00:22 cluster-database-dbname.html
-rw-r----- 1 postgres www-data 5.5M Jan  7 00:21 cluster-database-dbname.html
-rw-r----- 1 postgres www-data 8.0M Jan  7 00:22 cluster-database-dbname.html
-rw-r----- 1 postgres www-data 2.0M Jan  7 00:22 cluster-database-dbname.html
-rw-r----- 1 postgres www-data 8.0M Jan  7 00:22 cluster-database-dbname.html
-rw-r----- 1 postgres www-data 4.3M Jan  7 00:22 cluster-database-dbname.html
-rw-r----- 1 postgres www-data 286K Jan  7 00:22 cluster-database-dbname.html
-rw-r----- 1 postgres www-data  11M Jan  7 00:22 cluster-database-dbname.html
-rw-r----- 1 postgres www-data 9.3M Jan  7 00:21 cluster-database-dbname.html
-rw-r----- 1 postgres www-data 8.0M Jan  7 00:21 cluster-database-dbname.html
-rw-r----- 1 postgres www-data 2.1M Jan  7 00:22 cluster-database-dbname.html
-rw-r----- 1 postgres www-data 5.7M Jan  7 00:22 cluster-database-dbname.html
-rw-r----- 1 postgres www-data 603K Jan  7 00:21 cluster-nondefault-settings.html
-rw-r----- 1 postgres www-data 346K Jan  7 00:22 cluster-pgconf.html
-rw-r----- 1 postgres www-data 296K Jan  7 00:22 cluster-pghba.html
-rw-r----- 1 postgres www-data 4.4M Jan  7 00:21 cluster-settings.html
-rw-r----- 1 postgres www-data 6.6M Jan  7 00:22 dbname-tablespace-size.html
-rw-r----- 1 postgres www-data 6.7M Jan  7 00:21 cluster-xlog_files.html
-rw-r----- 1 postgres www-data 158K Jan  7 00:22 database-dbname.html
-rw-r----- 1 postgres www-data  42M Jan  7 00:22 database-dbname.html
-rw-r----- 1 postgres www-data  43M Jan  7 00:21 database-dbname.html
-rw-r----- 1 postgres www-data  44M Jan  7 00:22 database-dbname.html
-rw-r----- 1 postgres www-data  44M Jan  7 00:22 database-dbname.html
-rw-r----- 1 postgres www-data  42K Jan  7 00:22 dbname-index.html
-rw-r----- 1 postgres www-data  50K Jan  7 00:22 dbname-index-size.html
-rw-r----- 1 postgres www-data  43K Jan  7 00:22 dbname-index.html
-rw-r----- 1 postgres www-data  43K Jan  7 00:21 dbname-table-size.html
-rw-r----- 1 postgres www-data  47K Jan  7 00:22 dbname-index.html
-rw-r----- 1 postgres www-data    0 Jan  7 00:22 done
-rw-r----- 1 postgres www-data  43K Jan  7 00:22 dbname-index-size.html
-rw-r----- 1 postgres www-data  42K Jan  7 00:22 dbname-table-size.html
-rw-r----- 1 postgres www-data  79K Jan  7 00:22 index.html
-rw-r----- 1 postgres www-data 104K Jan  7 00:22 network-utilization-ens3.html
-rw-r----- 1 postgres www-data  95K Jan  7 00:22 network-utilization-lo.html
-rw-r----- 1 postgres www-data  43K Jan  7 00:21 dbname-index-size.html
-rw-r----- 1 postgres www-data  42K Jan  7 00:21 dbname-table-size.html
-rw-r----- 1 postgres www-data  42K Jan  7 00:22 dbname-index.html
-rw-r----- 1 postgres www-data  50K Jan  7 00:22 dbname-index-size.html
-rw-r----- 1 postgres www-data  43K Jan  7 00:22 dbname-index.html
-rw-r----- 1 postgres www-data  43K Jan  7 00:22 dbname-table-size.html
-rw-r----- 1 postgres www-data  44K Jan  7 00:21 dbname-index.html
-rw-r----- 1 postgres www-data 108K Jan  7 00:21 system-block.html
-rw-r----- 1 postgres www-data 112K Jan  7 00:22 system-commit_memory.html
-rw-r----- 1 postgres www-data  73K Jan  7 00:21 system-cpudevice-sda.html
-rw-r----- 1 postgres www-data 191K Jan  7 00:22 system-cpu.html
-rw-r----- 1 postgres www-data  74K Jan  7 00:21 system-cswch.html
-rw-r----- 1 postgres www-data 106K Jan  7 00:22 system-device-sda.html
-rw-r----- 1 postgres www-data 152K Jan  7 00:22 system-dirty.html
-rw-r----- 1 postgres www-data  99K Jan  7 00:22 system-fault.html
-rw-r----- 1 postgres www-data 131K Jan  7 00:21 system-load.html
-rw-r----- 1 postgres www-data 149K Jan  7 00:22 system-memory.html
-rw-r----- 1 postgres www-data 107K Jan  7 00:22 system-page.html
-rw-r----- 1 postgres www-data  72K Jan  7 00:21 system-pcrea.html
-rw-r----- 1 postgres www-data  70K Jan  7 00:22 system-process.html
-rw-r----- 1 postgres www-data  93K Jan  7 00:22 system-runqueue.html
-rw-r----- 1 postgres www-data 165K Jan  7 00:22 system-scanpage.html
-rw-r----- 1 postgres www-data  41K Jan  7 00:22 system-space.html
-rw-r----- 1 postgres www-data 103K Jan  7 00:22 system-space-sda2.html
-rw-r----- 1 postgres www-data 103K Jan  7 00:22 system-space-sda4.html
-rw-r----- 1 postgres www-data 104K Jan  7 00:21 system-srvtime-sda.html
-rw-r----- 1 postgres www-data 102K Jan  7 00:22 system-swap.html
-rw-r----- 1 postgres www-data  74K Jan  7 00:22 system-tpsdevice-sda.html
-rw-r----- 1 postgres www-data 136K Jan  7 00:22 system-tps.html

**Comment by darold** [comment] 2021-01-11 15:24
Hi,

You can download last pgcluu script from here https://raw.githubusercontent.com/darold/pgcluu/master/pgcluu and use it instead of yours currently installed. It will split the database info page into several pieces. I still have some other change minor change to publish a new release but normally the current code should be fully compatible, let me know if that's solve the issue.

**Comment by aschrafl** [comment] 2021-01-16 10:39
Hi,
I've run the updated version of the script and it generates smaller files. But it seems there is a loop somewhere that includes the main part of a section a second time.
Example:
On the database size page for a single database I get the rendering of the database size [Size of XYZ database] with the graph.
Then comes the copyright footer with the version info. This the HTML div's with the ID main-container with ID=slides and HTML-Tag footer within.

After the div ID=main-containter closes comes a full width grey bar similar to the section header [Size of XYZ database] but this time it is lacking the graph (there is space for it but no content).
After that the footer repeats itself as well but again 100% width this time.
These elements are a list element with the ID=database-size-slide and database-cache_ratio-slide. They seem to be attached to every page of the report.

**Comment by aschrafl** [comment] 2021-01-16 10:40
Update: with every new report copy generated these additional sections get added another time to the report-pages.

**Comment by darold** [comment] 2021-01-16 17:27
Slides database-info, database-size and database-cache_ratio are kept on the same HTML page but only visible when they are selected from the menu. Can you post the HTML page so that I can check if there is a particular case? Also what browser are you using?

**Comment by aschrafl** [comment] 2021-01-22 07:34
I'm using Firefox but the same happens on Chrome. These parts are multiple times in the HTML files and they get up to 20MB large. Is there any way of transmitting this file privately?

**Comment by darold** [comment] 2021-01-22 07:49
Yes, gilles AT darold DOT net

**Comment by aschrafl** [comment] 2021-01-22 09:20
perfect, sent you an email with the attachment. I've anonymized the DB names to database-[1-3]. Thanks

**Comment by darold** [comment] 2021-01-24 06:18
Do you have the same problem with other database-* files, like database-conn-postgres.html for example? Can you give a try to latest development code. Commit 2523ab4 removes a possible case for duplicate report but I don't think this is the reason of the problem.I suspect that the problem comes from the data file. If you can send me file pg_stat_database.csv to check the content and try to reproduce the issue.

**Comment by aschrafl** [comment] 2021-01-27 19:07
database-conn-postgres.html will crash my browser when I try to load it (original issue, also with the new code).
I've also tested with the latest commit and it still results in repetitive parts on the database-databasename.html files.

**Comment by darold** [comment] 2021-08-13 05:37
Closing, I'm not able to reproduce this issue and no one else reports that the same problem occurs

**Closed by darold** 2021-08-13 05:37 UTC
